sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
  - export HEXO_ALGOLIA_INDEXING_KEY=3e0f37de07a56a7044ee7df017b8af85
  - hexo algolia
  - pwd
  - echo "结束》》》========"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public